# Generated by Django 4.1.5 on 2023-01-15 16:41

from django.db import migrations, models
import recipe_book.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Favorite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': 'Избранное',
                'verbose_name_plural': 'Избранные',
            },
        ),
        migrations.CreateModel(
            name='Ingredient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=75, unique=True, verbose_name='Название')),
                ('measurement_unit', models.CharField(choices=[('g', 'г'), ('glass', 'стакан'), ('as_your_taste', 'по вкусу'), ('big_spoon', 'ст. л.'), ('pc', 'шт.'), ('ml', 'мл'), ('little_cpoon', 'ч. л.'), ('drop', 'капля'), ('asterisk', 'звездочка'), ('pinch', 'щепотка'), ('handful', 'горсть'), ('piece', 'кусок'), ('kg', 'кг'), ('package', 'пакет'), ('bundle', 'пучок'), ('slice', 'долька'), ('pot', 'банка'), ('packing', 'упаковка'), ('tooth', 'зубчик'), ('layer', 'пласт'), ('pack', 'пачка'), ('carcass', 'тушка'), ('pod', 'стручок'), ('twig', 'веточка'), ('bottle', 'бутылка'), ('l', 'л'), ('loaf', 'батон'), ('bag', 'пакетик'), ('leaf', 'лист'), ('stem', 'стебель')], default='g', max_length=80, verbose_name='Единица измерения')),
            ],
            options={
                'verbose_name': 'Ингридиент',
                'verbose_name_plural': 'Ингридиенты',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True, verbose_name='Название')),
                ('image', models.ImageField(default=None, null=True, upload_to=recipe_book.models.directory_path)),
                ('text', models.CharField(blank=True, max_length=500, null=True, verbose_name='Краткое описание рецепта (макс 500 символов)')),
                ('cooking_time', models.PositiveIntegerField(verbose_name='Время приготовления в минутах')),
            ],
            options={
                'verbose_name': 'Рецепт',
                'verbose_name_plural': 'Рецепты',
                'ordering': ('cooking_time',),
            },
        ),
        migrations.CreateModel(
            name='Shopping_cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': 'Список покупок',
                'verbose_name_plural': 'Список покупок',
            },
        ),
        migrations.CreateModel(
            name='Structure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.PositiveIntegerField(verbose_name='Количество')),
            ],
            options={
                'verbose_name': 'Состав рецепта',
                'verbose_name_plural': 'Составы рецепта',
                'ordering': ('recipe',),
            },
        ),
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': 'Подписка',
                'verbose_name_plural': 'Подписки',
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, unique=True, verbose_name='Тег')),
                ('color', models.CharField(max_length=16, unique=True, verbose_name='Цвет')),
                ('slug', models.SlugField(unique=True, verbose_name='Адрес')),
            ],
            options={
                'verbose_name': 'Тег',
                'verbose_name_plural': 'Теги',
            },
        ),
    ]
