# Generated by Django 4.1.5 on 2023-01-12 08:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import recipe_book.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Ingredient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=75, unique=True, verbose_name='Название')),
                ('quantity', models.IntegerField(verbose_name='Количество')),
                ('measurement_unit', models.CharField(choices=[('g', 'г'), ('glass', 'стакан'), ('as_your_taste', 'по вкусу'), ('big_spoon', 'ст. л.'), ('pc', 'шт.'), ('ml', 'мл'), ('little_cpoon', 'ч. л.'), ('drop', 'капля'), ('asterisk', 'звездочка'), ('pinch', 'щепотка'), ('handful', 'горсть'), ('piece', 'кусок'), ('ru', 'кг'), ('package', 'пакет'), ('bundle', 'пучок'), ('slice', 'долька'), ('pot', 'банка'), ('packing', 'упаковка'), ('tooth', 'зубчик'), ('layer', 'пласт'), ('pack', 'пачка'), ('carcass', 'тушка'), ('pod', 'стручок'), ('twig', 'веточка'), ('bottle', 'бутылка'), ('l', 'л'), ('loaf', 'батон'), ('bag', 'пакетик'), ('leaf', 'лист'), ('stem', 'стебель')], default='g', max_length=80, verbose_name='Единица измерения')),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='Тег')),
                ('color', models.CharField(max_length=16)),
                ('slug', models.SlugField(unique=True, verbose_name='Адрес')),
            ],
            options={
                'verbose_name': 'Тег',
                'verbose_name_plural': 'Теги',
            },
        ),
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True, verbose_name='Название')),
                ('image', models.ImageField(default=None, null=True, upload_to=recipe_book.models.directory_path)),
                ('description', models.CharField(blank=True, max_length=500, null=True, verbose_name='Краткое описание рецепта (макс 500 символов)')),
                ('cooking_time', models.PositiveIntegerField(verbose_name='Время приготовления в минутах')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('tags', models.ManyToManyField(to='recipe_book.tag')),
            ],
            options={
                'verbose_name': 'Рецепт',
                'verbose_name_plural': 'Рецепты',
                'ordering': ('cooking_time',),
            },
        ),
    ]
