# Generated by Django 4.1.5 on 2023-01-12 13:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recipe_book', '0003_rename_ingridients_structure_ingredients'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='structure',
            options={'ordering': ('recipe',), 'verbose_name': 'Состав рецепта', 'verbose_name_plural': 'Составы рецепта'},
        ),
        migrations.RenameField(
            model_name='structure',
            old_name='quantity',
            new_name='amount',
        ),
        migrations.AlterField(
            model_name='structure',
            name='ingredients',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='structure', to='recipe_book.ingredient'),
        ),
        migrations.AlterField(
            model_name='structure',
            name='recipe',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='structure', to='recipe_book.recipe'),
        ),
    ]
