# Generated by Django 4.1.5 on 2023-01-12 13:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipe_book', '0004_alter_structure_options_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recipe',
            old_name='description',
            new_name='text',
        ),
    ]
